name: pan_clock
description: Pan's Digital clock.
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  flare_flutter: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/day.jpg
    - assets/images/night.jpg
    - assets/animations/cloudy.flr
    - assets/animations/foggy.flr
    - assets/animations/rainy.flr
    - assets/animations/sunny.flr
    - assets/animations/snowy.flr
    - assets/animations/thunderstorm.flr
    - assets/animations/windy.flr

  fonts:
    - family: Heebo
      fonts:
        - asset: assets/fonts/Heebo-Bold.ttf
